// Adds IP address, command, and telemetry descriptions for Training Software

#ifndef ROVECOMMEXTENSION_H
#define ROVECOMMEXTENSION_H

#include <stdint.h>

#define RC_TRAININGSOFTWARE_FIRSTOCTET 192
#define RC_TRAININGSOFTWARE_SECONDOCTET 168
#define RC_TRAININGSOFTWARE_THIRDOCTET 3
#define RC_TRAININGSOFTWARE_FOURTHOCTET 200
#define RC_TRAININGSOFTWARE_IPADDRESS {192, 168, 3, 200}

////////////////////Commands
// -180 to 180 degrees
#define RC_TRAININGSOFTWARE_SERVOINCREMENT_DATA_ID 20001
#define RC_TRAININGSOFTWARE_SERVOINCREMENT_DATA_COUNT 1
#define RC_TRAININGSOFTWARE_SERVOINCREMENT_DATA_TYPE int16_t

////////////////////Telemetry
// Temperature
#define RC_TRAININGSOFTWARE_TEMPMEAS_DATA_ID 20101
#define RC_TRAININGSOFTWARE_TEMPMEAS_DATA_COUNT 1
#define RC_TRAININGSOFTWARE_TEMPMEAS_DATA_TYPE float

#endif /* ROVECOMMEXTENSION_H */
